focal_trials:
  - AWY1_DVPWA_2024
  - TCAP_2025_MANKS
  - 25_Big6_SVREC_SVREC
  - OHRWW_2025_SPO
  - CornellMaster_2025_McGowan
  - 24Crk_AY2-3
  - 2025_AYT_Aurora
  - YT_Urb_25
  - STP1_2025_MCG

traits:
  target_trait: value

model:
  use_ml: false
  lambda_factor: 1e-5
